version: 2.1
orbs:
  codecov: codecov/codecov@3.0.0

jobs:
  test-go:
    working_directory: ~/repo
    docker:
      - image: circleci/golang
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: go mod download
      - run:
          name: Run tests
          command: |
            mkdir -p /tmp/test-reports
            go test ./... -race -coverprofile=coverage.txt -covermode=atomic
      - run:
          name: Upload to Codecov
          command: bash <(curl -s https://codecov.io/bash)
      - store_test_results:
          path: /tmp/test-reports
  test-python:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo pip install pipenv pytest coverage
            pipenv install
      - run:
          name: Run tests and collect coverage
          command: |
            pwd
            coverage run -m pytest
            coverage xml
      - codecov/upload

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build-and-test: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - test-go
      - test-python
